### PR TITLE
feat: add youtube-title-grab script

### LINKED ISSUE #24: given youtube video ID, grab title and description
## user story

As someone who knows an ID of a youtube video, I can run a NodeJS command to grab the title and description, in order to save time on manual copy-pasting.

## acceptance test

Running `node grab-youtube-title.js https://youtu.be/5hVmeOCJjOU` we should see something like

    title: A Brief History of Quantum Mechanics - with Sean Carroll
    channel: The Royal Institution
    channel-id: UCYeF244yNGuFefuFKqxIAXw
    user: TheRoyalInstitution
    description: The mysterious world of quantum mechanics...

## use cases

Imagine an editor where we are taking some notes. A youtube video is mentioned there by its URL. When the mouse hovers over the video ID, we might want to show the author's name and title, and a part of description, in the on-hover popup.

A typical use case is also to show a title and a preview picture when a video URL is mentioned in a chat.

## discussion

I haven't investigated the subject of grabbing youtube metadata yet, but prelimiarily I see some possible directions:  
`1)` maybe there is an API by Google which we can reuse (via HTTP requiest or through a NodeJS library)  
`2)` might visit youtube with [playwright](https://www.npmjs.com/package/playwright)
`3)` might look at [youtube-dl](https://en.wikipedia.org/wiki/Youtube-dl)

<bountysource-plugin>

---
Did you fix this issue? Go claim the **[$123 bounty](https://www.bountysource.com/issues/97179388-given-youtube-video-id-grab-title-and-description?utm_campaign=plugin&utm_content=tracker%2F191328815&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F191328815&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by srevinsaju**
Fixes #24 
The pros of the PR is that, it doesnt need any authentication or API keys and are easier to maintain for a longer term.

### CODE REVIEW

**Comment by ArtemGr** [comment]
@srevinsaju , looks interesting, but make another PR into a separate file please (instead of patching grab-youtube-title.js), I'd like to evaluate the approaches separately (and possibly [later](https://www.scaledagileframework.com/set-based-design/)).

**Comment by srevinsaju** [comment]
Ok, shall I create another folder instead? Because the dependencies are smaller and different.

**Comment by ArtemGr** [comment]
@srevinsaju Yeah, go ahead!

**Comment by srevinsaju** [comment]
@ArtemGr done.

**Review by ArtemGr — APPROVED** [review]

**Pull request merged**
